# Random forest Classifier

In [1]:
# Libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [2]:
# import the dataset
df = pd.read_csv("driver_accident_risk_dataset.csv")
df

,driving_hours_per_day,rest_time_hours,past_accidents,speed_variance,weather_exposure_score,vehicle_condition_score,night_driving_ratio,route_difficulty,training_hours,fatigue_score,accident_risk
0,2.763083,7.366977,2,10.270900,3.755624,9.278428,0.752387,7.719204,106.754988,7.692765,0
1,9.799188,9.053273,3,37.140576,5.772123,8.964565,0.694126,8.102251,78.375794,1.428494,1
2,6.384092,4.675952,1,29.535183,8.062740,9.494488,0.799791,6.833505,158.189643,8.432308,1
3,9.234652,4.957026,0,18.788245,2.368312,2.248295,0.752922,5.908672,58.330077,2.935600,1
4,11.779895,8.971729,4,24.472747,0.233063,6.249916,0.455858,5.258977,100.658252,1.283160,0
...,...,...,...,...,...,...,...,...,...,...,...
79995,9.364343,8.428290,1,34.419623,0.929625,9.674138,0.928645,4.488851,168.411972,6.555143,1
79996,11.845030,7.624478,1,27.642098,1.737630,1.885311,0.974523,7.873386,0.686898,5.968663,1
79997,10.570447,8.991270,1,25.467171,0.909142,7.910915,0.060114,2.923822,194.466429,5.420102,0
79998,11.882853,7.753900,4,7.365288,0.264087,2.903275,0.532276,9.512072,77.318064,0.383967,1
79999,9.844913,9.491196,4,35.889040,2.550161,8.069088,0.643171,4.012507,65.748537,5.073644,1

In [3]:
df.accident_risk.unique()

array([0, 1])

In [4]:
x = df.drop("accident_risk", axis = 1)
y = df.accident_risk

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [6]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [7]:
rf = RandomForestClassifier(n_estimators = 100, n_jobs = -1, max_samples = 0.8, max_features = 0.5)

In [8]:
rf.fit(x_train_scaled, y_train)

RandomForestClassifier(max_features=0.5, max_samples=0.8, n_jobs=-1)

In [9]:
rf.score(x_test_scaled, y_test)

0.999625

# Random forest Regressor

In [10]:
from sklearn.ensemble import RandomForestRegressor

In [11]:
df = pd.read_csv("housing_data_50k_extended.csv")
df

,area,bedrooms,age,price,num_floors,zip_code,furnishing_status,property_type,green_area_percent
0,1660,2,18,335000,4,20001,0,3,34
1,4572,6,25,890000,5,20002,0,1,46
2,3892,5,10,804000,3,30002,2,1,37
3,1266,3,42,233000,1,40001,0,2,42
4,4244,6,31,870000,1,10005,0,0,24
...,...,...,...,...,...,...,...,...,...
49995,959,1,35,116000,1,30001,2,1,22
49996,4372,6,29,911000,3,10003,2,2,23
49997,2289,6,33,484000,1,10003,2,1,47
49998,3695,6,17,743000,2,20001,1,2,6
49999,4728,8,2,1015000,2,10005,1,2,12

In [12]:
x = df.drop("price", axis =1)
y = df.price

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 40)

In [15]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [16]:
rfr = RandomForestRegressor(n_estimators = 50, n_jobs = -1, max_samples = 0.7, max_features = 0.6)
rfr.fit(x_train_scaled, y_train)

RandomForestRegressor(max_features=0.6, max_samples=0.7, n_estimators=50,
                      n_jobs=-1)

In [17]:
rfr.score(x_test_scaled, y_test)

0.9901083670862556

# Bagging

In [18]:
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier

In [19]:
df = pd.read_csv("driver_accident_risk_dataset.csv")
df

,driving_hours_per_day,rest_time_hours,past_accidents,speed_variance,weather_exposure_score,vehicle_condition_score,night_driving_ratio,route_difficulty,training_hours,fatigue_score,accident_risk
0,2.763083,7.366977,2,10.270900,3.755624,9.278428,0.752387,7.719204,106.754988,7.692765,0
1,9.799188,9.053273,3,37.140576,5.772123,8.964565,0.694126,8.102251,78.375794,1.428494,1
2,6.384092,4.675952,1,29.535183,8.062740,9.494488,0.799791,6.833505,158.189643,8.432308,1
3,9.234652,4.957026,0,18.788245,2.368312,2.248295,0.752922,5.908672,58.330077,2.935600,1
4,11.779895,8.971729,4,24.472747,0.233063,6.249916,0.455858,5.258977,100.658252,1.283160,0
...,...,...,...,...,...,...,...,...,...,...,...
79995,9.364343,8.428290,1,34.419623,0.929625,9.674138,0.928645,4.488851,168.411972,6.555143,1
79996,11.845030,7.624478,1,27.642098,1.737630,1.885311,0.974523,7.873386,0.686898,5.968663,1
79997,10.570447,8.991270,1,25.467171,0.909142,7.910915,0.060114,2.923822,194.466429,5.420102,0
79998,11.882853,7.753900,4,7.365288,0.264087,2.903275,0.532276,9.512072,77.318064,0.383967,1
79999,9.844913,9.491196,4,35.889040,2.550161,8.069088,0.643171,4.012507,65.748537,5.073644,1

In [20]:
x = df.drop("accident_risk", axis = 1)
y = df.accident_risk

In [21]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 42)

In [22]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [24]:
base_model = KNeighborsClassifier(n_neighbors = 5)

bagging_model = BaggingClassifier(estimator=base_model, n_estimators = 20, max_samples = 0.8)

bagging_model.fit(x_train_scaled, y_train)

BaggingClassifier(estimator=KNeighborsClassifier(), max_samples=0.8,
                  n_estimators=20)

In [25]:
bagging_model.score(x_test_scaled, y_test)

0.9005